---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ref: https://github.com/stolostron/siteconfig/blob/main/docs/argocd.md#prepare-git-repository
resources:
  - ns.yaml
  - secrets.yaml
  - vault.yaml
  - clusterinstance.yaml


# Ref: https://github.com/stolostron/siteconfig/blob/main/docs/argocd.md#generate-extra-manifests-configmap-using-kustomize
configMapGenerator:
  - files:
      - extra-manifests-4.18/00-kernel-64k-pages-master.yaml
      - extra-manifests-4.18/01-container-mount-ns-and-kubelet-conf-master.yaml
      - extra-manifests-4.18/01-container-mount-ns-and-kubelet-conf-worker.yaml
      - extra-manifests-4.18/01-disk-encryption-pcr-rebind-master.yaml
      - extra-manifests-4.18/01-disk-encryption-pcr-rebind-worker.yaml
      - extra-manifests-4.18/03-sctp-machine-config-master.yaml
      - extra-manifests-4.18/03-sctp-machine-config-worker.yaml
      - extra-manifests-4.18/06-kdump-master.yaml
      - extra-manifests-4.18/06-kdump-worker.yaml
 # Remove x86 specific SRIOV kernel args
 #     - extra-manifests-4.18/07-sriov-related-kernel-args-master.yaml
 #     - extra-manifests-4.18/07-sriov-related-kernel-args-worker.yaml
      - extra-manifests-4.18/08-set-rcu-normal-master.yaml
      - extra-manifests-4.18/08-set-rcu-normal-worker.yaml
      - extra-manifests-4.18/09-openshift-marketplace-ns.yaml
      - extra-manifests-4.18/99-crio-disable-wipe-worker.yaml
      - extra-manifests-4.18/99-sync-time-once-master.yaml
      - extra-manifests-4.18/99-crio-disable-wipe-master.yaml
      - extra-manifests-4.18/99-sync-time-once-worker.yaml
      - extra-manifests-4.18/enable-crun-master.yaml
      - extra-manifests-4.18/enable-crun-worker.yaml
      - extra-manifests-4.18/master-core-password.yaml
    name: ran-rds-manifests
    namespace: hp-arm1

generatorOptions:
  disableNameSuffixHash: true
