#---
apiVersion: v1
kind: Secret
metadata:
  name: hp-arm1-worker
  namespace: hp-arm1
data:
  username: ""
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: hp-arm1
stringData:
  .dockerconfigjson: '{""}'
